### ISSUE TITLE
# Checklist that we need to do for this week

### ISSUE THREAD

**Issue by SuzyZou** [chesterornes/.github#1]
- [ ] [Watch the video ](https://www.youtube.com/watch?v=xlAXldBt7I0)
- [ ] [ Read the algorithmic trading architecture provided by AWS](https://aws.amazon.com/blogs/industries/algorithmic-trading-on-aws-with-amazon-sagemaker-and-aws-data-exchange/)
- [ ] [Read the content in the AlgoOpt repository](https://github.com/chesterornes/AlgoOpt)
- [ ] [Read the content in the TreadingStratageAnalysis repository](https://github.com/chesterornes/TradingStrategyAnalysis)

**Comment by callforhelp123** [comment]
thanks for giving us these tasks Suzy, we'll get them done by the end of  the week!
